### PR TITLE
Various enhancements

### PR DESCRIPTION
**Pull request by UndeadZeratul**
- Update ZScript to v4.11, use foreach loops
- Allow multiple custom lumps to be read
- Use Translations instead of new sprites
- Add to HD Addons Menu

### CODE REVIEW

**Comment by dastrukar** [comment]
Do you mind changing some parts of the code that aren't consistent with the rest of the code style?
I noticed that some of the parts were changed from
```csharp
if (condition)
    code;
    
if (condition)
{
    code;
}
```
to
```csharp
if (condition) code;
    
if (condition) {
    code;
}
```
Would probably be better to keep the code style consistent throughout (and sorry if i wasn't consistent with the coding style)

**Comment by UndeadZeratul** [comment]
Totally fair, and honestly I only changed them since I was looking at those specific blocks and was trying to make things easier to parse.

Do you have a preference on code style?  I'll update things however you like them to look.  Really wish there was a formatter/Linter for ZScript lol

**Comment by dastrukar** [comment]
I think you can just change it back to how it was before, and I think you can just look at the diff to see how it should be styled?
Or I suppose you could also look at the example I previously provided in my reply if that works?

**Comment by UndeadZeratul** [comment]
How's that?  I found a few more for loops that could be enhanced to use foreach loops as well, if you'd prefer to keep the old loops just let me know

**Comment by dastrukar** [comment]
The foreach loops are fine, if anything, I'd say they're an improvement over the for loops :]
Well, everything else seems fine to me. Merging.

**Pull request merged**
